# André Dexheimer Carneiro
# 00243653

# makefile para a geração dos programas de teste 


CC=gcc
LIB_DIR=../lib


1teste:	

	$(CC) -o 1teste_thread 1teste_thread.c -L$(LIB_DIR) -lcthread -Wall

	./1teste_thread


2teste:

	$(CC) -o 2teste_thread 2teste_thread.c -L$(LIB_DIR) -lcthread -Wall

	./2teste_thread

3teste:

	$(CC) -o 3teste_thread 3teste_thread.c -L$(LIB_DIR) -lcthread -Wall

	./3teste_thread
